---
- hosts: localhost
  tasks:
    - name: Install specified python requirements in indicated (virtualenv)
      pip:
        requirements: /srv/jenkins/requirements.txt
        virtualenv: /venvs/jenkins_env
        virtualenv_python: python3
