"""empty message

Revision ID: 745dc38b7c67
Revises: e39b65c9b904
Create Date: 2022-04-27 14:19:47.292481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745dc38b7c67'
down_revision = 'e39b65c9b904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'workout_week')
    op.drop_column('workout', 'workout_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workout_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('workout_week', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
