"""empty message

Revision ID: 75762fdbb37b
Revises: 
Create Date: 2022-04-01 18:46:23.274764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75762fdbb37b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.DateTime(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep',
    sa.Column('id', sa.DateTime(), nullable=False),
    sa.Column('day_id', sa.DateTime(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('total_rem_sleep', sa.DateTime(), nullable=True),
    sa.Column('total_deep_sleep', sa.DateTime(), nullable=True),
    sa.Column('sleep_efficiency', sa.Integer(), nullable=True),
    sa.Column('restlessness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep')
    op.drop_table('day')
    # ### end Alembic commands ###
