"""empty message

Revision ID: 8f8ed6dd7ab4
Revises: 265ef7b5e260
Create Date: 2022-04-03 16:32:11.065159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8ed6dd7ab4'
down_revision = '265ef7b5e260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Date(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep',
    sa.Column('id', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('total_rem_sleep', sa.Integer(), nullable=True),
    sa.Column('total_deep_sleep', sa.DateTime(), nullable=True),
    sa.Column('sleep_efficiency', sa.DateTime(), nullable=True),
    sa.Column('restlessness', sa.Integer(), nullable=True),
    sa.Column('rem_score', sa.Integer(), nullable=True),
    sa.Column('deep_score', sa.Integer(), nullable=True),
    sa.Column('total_sleep', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep')
    op.drop_table('log')
    # ### end Alembic commands ###
