"""empty message

Revision ID: 070ed1a9cdbb
Revises: 903ec17393e1
Create Date: 2022-05-03 18:12:37.434469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070ed1a9cdbb'
down_revision = '903ec17393e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('stress', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('food_cutoff', sa.Float(), nullable=True))
    op.add_column('workout', sa.Column('grade', sa.Integer(), nullable=True))
    op.drop_column('workout', 'intensity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('workout', 'grade')
    op.drop_column('sleep', 'food_cutoff')
    op.drop_column('log', 'stress')
    # ### end Alembic commands ###
