"""empty message

Revision ID: 0a28039c14c9
Revises: ccbb9fda3a8f
Create Date: 2022-09-29 12:04:13.025340

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0a28039c14c9'
down_revision = 'ccbb9fda3a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=280,
                                               increment=1,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('readiness',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=280,
                                               increment=1,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('sleep',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=280,
                                               increment=1,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.drop_constraint('user_id_key', 'user', type_='unique')
    op.alter_column('weights',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=280,
                                               increment=1,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('workout',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=280,
                                               increment=1,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=400,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('weights',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=400,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.create_unique_constraint('user_id_key', 'user', ['id'])
    op.alter_column('sleep',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('readiness',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('log',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###
