"""empty message

Revision ID: 0b082426d734
Revises: ec8ea234a408
Create Date: 2022-09-28 16:09:55.695390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b082426d734'
down_revision = 'ec8ea234a408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('day_id', sa.Integer(), nullable=True))
    op.add_column('readiness', sa.Column('day_id', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('day_id', sa.Integer(), nullable=True))
    op.add_column('tag', sa.Column('day_id', sa.Integer(), nullable=True))
    op.add_column('workout', sa.Column('day_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'day_id')
    op.drop_column('tag', 'day_id')
    op.drop_column('sleep', 'day_id')
    op.drop_column('readiness', 'day_id')
    op.drop_column('log', 'day_id')
    # ### end Alembic commands ###
