"""empty message

Revision ID: 0ecb4e38e2b1
Revises: b87a2bfecca8
Create Date: 2022-09-16 14:16:46.781839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecb4e38e2b1'
down_revision = 'b87a2bfecca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('date_str'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='days_pkey'),
    sa.UniqueConstraint('date', name='days_date_key'),
    sa.UniqueConstraint('date_str', name='days_date_str_key')
    )
    op.drop_table('day')
    # ### end Alembic commands ###
