"""empty message

Revision ID: 129d08fd0675
Revises: 7ed47b8f8a9b
Create Date: 2022-04-19 19:36:16.408067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129d08fd0675'
down_revision = '7ed47b8f8a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workout_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'workout_id')
    # ### end Alembic commands ###
