"""empty message

Revision ID: 163b5fe7a33c
Revises: 7f09866a40d4
Create Date: 2023-02-02 10:49:55.519987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163b5fe7a33c'
down_revision = '7f09866a40d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_tag_key', 'tag', type_='unique')
    op.add_column('weights', sa.Column('og_workout_id', sa.Integer(), nullable=True))
    op.add_column('weights', sa.Column('og_workout_week', sa.Integer(), nullable=True))
    op.add_column('weights', sa.Column('from_base', sa.Boolean(), nullable=True))
    op.add_column('workout', sa.Column('weights_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'weights_data')
    op.drop_column('weights', 'from_base')
    op.drop_column('weights', 'og_workout_week')
    op.drop_column('weights', 'og_workout_id')
    op.create_unique_constraint('tag_tag_key', 'tag', ['tag'])
    # ### end Alembic commands ###
