"""empty message

Revision ID: 1ba5ef0bedbe
Revises: b7fce7a277a4
Create Date: 2022-04-14 21:42:14.323901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba5ef0bedbe'
down_revision = 'b7fce7a277a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workout_log', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'workout_log')
    # ### end Alembic commands ###
