"""empty message

Revision ID: 253a6619ae8d
Revises: 541f799e3970
Create Date: 2022-04-03 17:37:28.733457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253a6619ae8d'
down_revision = '541f799e3970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('rem_score', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('deep_score', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('total_sleep', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep', 'total_sleep')
    op.drop_column('sleep', 'deep_score')
    op.drop_column('sleep', 'rem_score')
    # ### end Alembic commands ###
