"""empty message

Revision ID: 380538cc5f35
Revises: 6f6af73b317f
Create Date: 2022-09-13 08:48:35.198167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380538cc5f35'
down_revision = '6f6af73b317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'user', ['user_id'], ['id'])
    op.add_column('readiness', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'readiness', 'user', ['user_id'], ['id'])
    op.add_column('sleep', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sleep', 'user', ['user_id'], ['id'])
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'])
    op.add_column('template', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'template', 'user', ['user_id'], ['id'])
    op.add_column('weights', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weights', 'user', ['user_id'], ['id'])
    op.add_column('workout', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workout', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.drop_column('workout', 'user_id')
    op.drop_constraint(None, 'weights', type_='foreignkey')
    op.drop_column('weights', 'user_id')
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.drop_column('template', 'user_id')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    op.drop_constraint(None, 'sleep', type_='foreignkey')
    op.drop_column('sleep', 'user_id')
    op.drop_constraint(None, 'readiness', type_='foreignkey')
    op.drop_column('readiness', 'user_id')
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
