"""empty message

Revision ID: 3cec7c660792
Revises: 71af21d99e2a
Create Date: 2022-09-14 17:31:17.183708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cec7c660792'
down_revision = '71af21d99e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event', sa.JSON(), nullable=True))
    op.drop_column('events', 'events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('events', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_column('events', 'event')
    # ### end Alembic commands ###
