"""empty message

Revision ID: 4163eb641f1e
Revises: fb3d4c6f0913
Create Date: 2023-01-30 16:28:07.344539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4163eb641f1e'
down_revision = 'fb3d4c6f0913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('og_workout_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'og_workout_id')
    # ### end Alembic commands ###
