"""empty message

Revision ID: 538cedf856c8
Revises: 8f8ed6dd7ab4
Create Date: 2022-04-03 16:33:42.275552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538cedf856c8'
down_revision = '8f8ed6dd7ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('rem_score', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('deep_score', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('total_sleep', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep', 'total_sleep')
    op.drop_column('sleep', 'deep_score')
    op.drop_column('sleep', 'rem_score')
    # ### end Alembic commands ###
