"""empty message

Revision ID: 541f799e3970
Revises: dc19ce740918
Create Date: 2022-04-03 17:35:45.974813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541f799e3970'
down_revision = 'dc19ce740918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('rem_score', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('deep_score', sa.Integer(), nullable=True))
    op.add_column('sleep', sa.Column('total_sleep', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep', 'total_sleep')
    op.drop_column('sleep', 'deep_score')
    op.drop_column('sleep', 'rem_score')
    # ### end Alembic commands ###
