"""empty message

Revision ID: 5adf8048cbfe
Revises: 983a5af8b738
Create Date: 2022-04-24 20:29:55.535013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adf8048cbfe'
down_revision = '983a5af8b738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercises', sa.String(), nullable=True),
    sa.Column('set_ranges', sa.String(), nullable=True),
    sa.Column('reps', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('workout_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    # ### end Alembic commands ###
