"""empty message

Revision ID: 6a01ef2bc911
Revises: fc43e55cc47d
Create Date: 2022-05-27 20:38:54.635133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a01ef2bc911'
down_revision = 'fc43e55cc47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('template_name', sa.String(), nullable=True))
    op.add_column('weights', sa.Column('row_nums', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'row_nums')
    op.drop_column('weights', 'template_name')
    # ### end Alembic commands ###
