"""empty message

Revision ID: 71af21d99e2a
Revises: d4e22b6eb1d4
Create Date: 2022-09-14 13:44:47.134504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71af21d99e2a'
down_revision = 'd4e22b6eb1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
