"""empty message

Revision ID: 79bfb0b3f51e
Revises: 070ed1a9cdbb
Create Date: 2022-05-10 21:32:39.533640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bfb0b3f51e'
down_revision = '070ed1a9cdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('datetime_sleep', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep', 'datetime_sleep')
    # ### end Alembic commands ###
