"""empty message

Revision ID: 7ed47b8f8a9b
Revises: 1ba5ef0bedbe
Create Date: 2022-04-15 13:24:23.494797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed47b8f8a9b'
down_revision = '1ba5ef0bedbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readiness', sa.Column('readiness_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readiness', 'readiness_score')
    # ### end Alembic commands ###
