"""empty message

Revision ID: 7f4e10772bf3
Revises: bda7f0458fd4
Create Date: 2022-10-12 09:45:04.172469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4e10772bf3'
down_revision = 'bda7f0458fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_id_key', 'tag', type_='unique')
    op.add_column('weights', sa.Column('exercises_old', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'exercises_old')
    op.create_unique_constraint('tag_id_key', 'tag', ['id'])
    # ### end Alembic commands ###
