"""empty message

Revision ID: 8a4cc2ab6c72
Revises: 9f5faf2f9526
Create Date: 2022-04-27 16:03:50.852785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4cc2ab6c72'
down_revision = '9f5faf2f9526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('subbed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'subbed')
    # ### end Alembic commands ###
