"""empty message

Revision ID: 8e87c011b9c8
Revises: 45ed5a5ae632
Create Date: 2022-10-26 11:54:36.748031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e87c011b9c8'
down_revision = '45ed5a5ae632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'score')
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
