"""empty message

Revision ID: 8fd6d842e7d3
Revises: 8e87c011b9c8
Create Date: 2022-10-26 11:59:20.175147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd6d842e7d3'
down_revision = '8e87c011b9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('subclass', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'subclass')
    # ### end Alembic commands ###
