"""empty message

Revision ID: 983a5af8b738
Revises: 129d08fd0675
Create Date: 2022-04-21 17:31:18.362650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983a5af8b738'
down_revision = '129d08fd0675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workout_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'workout_week')
    # ### end Alembic commands ###
