"""empty message

Revision ID: 9935c7ccb825
Revises: cd9bb04cfef4
Create Date: 2022-09-29 13:47:00.704492

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9935c7ccb825'
down_revision = 'cd9bb04cfef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('readiness',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('sleep',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('weights',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('workout',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('weights',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('sleep',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('readiness',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('log',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###
