"""empty message

Revision ID: 9f5faf2f9526
Revises: e22f1dccbb61
Create Date: 2022-04-27 16:02:31.238046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5faf2f9526'
down_revision = 'e22f1dccbb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('subbed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'subbed')
    # ### end Alembic commands ###
