"""empty message

Revision ID: ab5289441f00
Revises: 8a4cc2ab6c72
Create Date: 2022-04-27 17:11:06.475759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab5289441f00'
down_revision = '8a4cc2ab6c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weights', 'set_ranges',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('weights', 'reps',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('weights', 'weight',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weights', 'weight',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('weights', 'reps',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('weights', 'set_ranges',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    # ### end Alembic commands ###
