"""empty message

Revision ID: bc428a8940f9
Revises: e0b385dc2f5b
Create Date: 2022-09-29 14:54:09.111184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc428a8940f9'
down_revision = 'e0b385dc2f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_workout', sa.Column('template_id', sa.Integer(), nullable=True))
    op.drop_constraint('base_workout_template_name_fkey', 'base_workout', type_='foreignkey')
    op.create_foreign_key(None, 'base_workout', 'template', ['template_id'], ['id'])
    op.drop_column('base_workout', 'template_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_workout', sa.Column('template_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'base_workout', type_='foreignkey')
    op.create_foreign_key('base_workout_template_name_fkey', 'base_workout', 'template', ['template_name'], ['id'])
    op.drop_column('base_workout', 'template_id')
    # ### end Alembic commands ###
