"""empty message

Revision ID: bda7f0458fd4
Revises: e0a90fa59b48
Create Date: 2022-10-12 09:44:15.527038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda7f0458fd4'
down_revision = 'e0a90fa59b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_id_key', 'tag', type_='unique')
    op.add_column('weights', sa.Column('exercises_old', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'exercises_old')
    op.create_unique_constraint('tag_id_key', 'tag', ['id'])
    # ### end Alembic commands ###
