"""empty message

Revision ID: c29738f02d99
Revises: 8fd6d842e7d3
Create Date: 2023-01-23 18:02:42.705757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29738f02d99'
down_revision = '8fd6d842e7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('weights_data', sa.Boolean(), nullable=True))
    op.drop_column('workout', 'workout_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('workout_log', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workout', 'weights_data')
    # ### end Alembic commands ###
