"""empty message

Revision ID: ccbb9fda3a8f
Revises: e1d47ce259b3
Create Date: 2022-09-29 09:35:52.664520

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ccbb9fda3a8f'
down_revision = 'e1d47ce259b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_id_key', 'log', type_='unique')
    op.drop_constraint('readiness_id_key', 'readiness', type_='unique')
    op.drop_constraint('sleep_id_key', 'sleep', type_='unique')
    op.drop_constraint('tag_id_key', 'tag', type_='unique')
    op.drop_constraint('workout_id_key', 'workout', type_='unique')
    op.execute(
        "SELECT setval(pg_get_serial_sequence('tag', 'id'), (SELECT max(id) from tag));;"
    )
    op.execute("SELECT setval('log_id_seq', (SELECT max('id') from log));")
    op.execute("SELECT setval(‘sleep_id_seq‘, (SELECT max('id') from sleep));")
    op.execute(
        "SELECT setval(‘readiness_id_seq‘, (SELECT max('id') from readiness));"
    )
    op.execute(
        "SELECT setval('workout_id_seq‘, (SELECT max('id') from workout));")
    op.execute(
        "SELECT setval(‘weights_id_seq‘, (SELECT max('id') from weights));")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('workout_id_key', 'workout', ['id'])
    op.create_unique_constraint('tag_id_key', 'tag', ['id'])
    op.create_unique_constraint('sleep_id_key', 'sleep', ['id'])
    op.create_unique_constraint('readiness_id_key', 'readiness', ['id'])
    op.create_unique_constraint('log_id_key', 'log', ['id'])
    # ### end Alembic commands ###
