"""empty message

Revision ID: cd9bb04cfef4
Revises: 0a28039c14c9
Create Date: 2022-09-29 12:26:28.790453

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cd9bb04cfef4'
down_revision = '0a28039c14c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS workout_id_seq OWNED BY workout.id; SELECT setval(workout_id_seq, (SELECT max(id) from workout)); ALTER TABLE workout ALTER COLUMN id SET DEFAULT nextval('workout_id_seq');"
    )
    op.execute()
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS weights_id_seq OWNED BY weights.id; SELECT setval(weights_id_seq, (SELECT max(id) from weights)); ALTER TABLE weights ALTER COLUMN id SET DEFAULT nextval('workout_id_seq');"
    )
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS sleep_id_seq OWNED BY sleep.id; SELECT setval(sleep_id_seq, (SELECT max(id) from workout)); ALTER TABLE sleep ALTER COLUMN id SET DEFAULT nextval('sleep_id_seq');"
    )
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS readiness_id_seq OWNED BY readiness.id; SELECT setval(readiness_id_seq, (SELECT max(id) from readiness)); ALTER TABLE readiness ALTER COLUMN id SET DEFAULT nextval('readiness_id_seq');"
    )
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS log_id_seq OWNED BY log.id; SELECT setval(log_id_seq, (SELECT max(id) from log)); ALTER TABLE log ALTER COLUMN id SET DEFAULT nextval('log_id_seq');"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('weights',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('sleep',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('readiness',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('log',
                    'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(always=True,
                                               start=1,
                                               increment=1,
                                               minvalue=1,
                                               maxvalue=9223372036854775807,
                                               cycle=False,
                                               cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###
