"""empty message

Revision ID: e0a90fa59b48
Revises: d9e46efc6c85
Create Date: 2022-10-12 09:12:30.754817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a90fa59b48'
down_revision = 'd9e46efc6c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('exercises_old', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'exercises_old')
    # ### end Alembic commands ###
