"""empty message

Revision ID: e1d47ce259b3
Revises: 3758156ad41e
Create Date: 2022-09-29 08:51:06.064774

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e1d47ce259b3'
down_revision = '3758156ad41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SELECT setval(‘“tag_id_seq”‘, (SELECT max(“id”) from tag));")
    op.execute("SELECT setval(‘“log_id_seq”‘, (SELECT max(“id”) from log));")
    op.execute(
        "SELECT setval(‘“sleep_id_seq”‘, (SELECT max(“id”) from sleep));")
    op.execute(
        "SELECT setval(‘“readiness_id_seq”‘, (SELECT max(“id”) from readiness));"
    )
    op.execute(
        "SELECT setval(‘“workout_id_seq”‘, (SELECT max(“id”) from workout));")
    op.execute(
        "SELECT setval(‘“weights_id_seq”‘, (SELECT max(“id”) from weights));")
    op.create_unique_constraint(None, 'log', ['id'])
    op.create_unique_constraint(None, 'readiness', ['id'])
    op.create_unique_constraint(None, 'sleep', ['id'])
    op.create_unique_constraint(None, 'workout', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout', type_='unique')
    op.drop_constraint(None, 'sleep', type_='unique')
    op.drop_constraint(None, 'readiness', type_='unique')
    op.drop_constraint(None, 'log', type_='unique')
    # ### end Alembic commands ###
