"""empty message

Revision ID: ec8ea234a408
Revises: c05800f2e288
Create Date: 2022-09-28 16:07:03.956202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8ea234a408'
down_revision = 'c05800f2e288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('day_id', sa.Integer(), nullable=False))
    op.drop_column('log', 'id')
    op.add_column('readiness', sa.Column('day_id', sa.Integer(), nullable=False))
    op.drop_column('readiness', 'id')
    op.add_column('sleep', sa.Column('day_id', sa.Integer(), nullable=False))
    op.drop_column('sleep', 'id')
    op.add_column('tag', sa.Column('day_id', sa.Integer(), nullable=False))
    op.drop_constraint('tag_id_key', 'tag', type_='unique')
    op.create_unique_constraint(None, 'tag', ['day_id'])
    op.drop_column('tag', 'id')
    op.drop_constraint('tags_tag_id_fkey', 'tags', type_='foreignkey')
    op.drop_constraint('tags_log_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'log', ['log_id'], ['day_id'])
    op.create_foreign_key(None, 'tags', 'tag', ['tag_id'], ['day_id'])
    op.add_column('workout', sa.Column('day_id', sa.Integer(), nullable=False))
    op.drop_column('workout', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('workout', 'day_id')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_log_id_fkey', 'tags', 'log', ['log_id'], ['id'])
    op.create_foreign_key('tags_tag_id_fkey', 'tags', 'tag', ['tag_id'], ['id'])
    op.add_column('tag', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'tag', type_='unique')
    op.create_unique_constraint('tag_id_key', 'tag', ['id'])
    op.drop_column('tag', 'day_id')
    op.add_column('sleep', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sleep', 'day_id')
    op.add_column('readiness', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('readiness', 'day_id')
    op.add_column('log', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('log', 'day_id')
    # ### end Alembic commands ###
