"""empty message

Revision ID: ee004985f7ca
Revises: 9f33f2be6edf
Create Date: 2022-09-29 14:36:40.468790

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee004985f7ca'
down_revision = '9f33f2be6edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('base_workout_template_name_fkey',
                       'base_workout',
                       type_='foreignkey')

    op.alter_column('base_workout',
                    'template_name',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.create_foreign_key(None, 'base_workout', 'template', ['template_name'],
                          ['template_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_workout', type_='foreignkey')
    op.create_foreign_key('base_workout_template_name_fkey', 'base_workout',
                          'template', ['template_name'], ['id'])
    op.alter_column('base_workout',
                    'template_name',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
