"""empty message

Revision ID: f33d55cc3e59
Revises: 5f204e2b605a
Create Date: 2022-04-07 22:10:53.470228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33d55cc3e59'
down_revision = '5f204e2b605a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.DATETIME(), nullable=False),
    sa.Column('focus', sa.INTEGER(), nullable=True),
    sa.Column('mood', sa.INTEGER(), nullable=True),
    sa.Column('energy', sa.INTEGER(), nullable=True),
    sa.Column('journal', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
