"""empty message

Revision ID: f7ae9ac259b8
Revises: bc428a8940f9
Create Date: 2022-10-03 17:38:08.806930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7ae9ac259b8'
down_revision = 'bc428a8940f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('rep_range', sa.String(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('reps_improve', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_improve', sa.Boolean(), nullable=True),
    sa.Column('weights_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weights_id'], ['weights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('weights', sa.Column('base_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weights', 'base_workout', ['base_id'], ['id'])
    op.drop_column('weights', 'exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('exercises', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weights', type_='foreignkey')
    op.drop_column('weights', 'base_id')
    op.drop_table('exercise')
    # ### end Alembic commands ###
