"""empty message

Revision ID: fb3d4c6f0913
Revises: 9af784419065
Create Date: 2023-01-24 14:06:23.532006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3d4c6f0913'
down_revision = '9af784419065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weights', sa.Column('from_base', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weights', 'from_base')
    # ### end Alembic commands ###
