"""empty message

Revision ID: fc43e55cc47d
Revises: 79bfb0b3f51e
Create Date: 2022-05-11 11:28:54.088620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc43e55cc47d'
down_revision = '79bfb0b3f51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('seconds_sleep', sa.Integer(), nullable=True))
    op.drop_column('sleep', 'datetime_sleep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep', sa.Column('datetime_sleep', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('sleep', 'seconds_sleep')
    # ### end Alembic commands ###
