"""empty message

Revision ID: fd75700feeb0
Revises: ee004985f7ca
Create Date: 2022-09-29 14:43:26.103620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd75700feeb0'
down_revision = 'ee004985f7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_workout', 'template_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('base_workout_template_name_fkey', 'base_workout', type_='foreignkey')
    op.create_foreign_key(None, 'base_workout', 'template', ['template_name'], ['template_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_workout', type_='foreignkey')
    op.create_foreign_key('base_workout_template_name_fkey', 'base_workout', 'template', ['template_name'], ['id'])
    op.alter_column('base_workout', 'template_name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
